server:
  address: "0.0.0.0"
  port: "80"
placesApi:
  host: http://go-explore.ru/proxy/maps/maps/api/
logger:
  format: plain
  level: 4
  name: place
  output: ./log/places.log
db:
  url: "@DB_URL@"
  port: "@DB_PORT@"
  user: "@DB_USER@"
  password: "@DB_PASSWORD@"
  name: "@DB_NAME@"
